#define dxdot0_dflux_r0 dxdotdw[0]
#define dxdot1_dflux_r0 dxdotdw[1]
#define dxdot2_dflux_r0 dxdotdw[2]
#define dxdot0_dflux_r1 dxdotdw[3]
#define dxdot1_dflux_r1 dxdotdw[4]
#define dxdot2_dflux_r1 dxdotdw[5]