# SPARCED Standard
# Last update: 2025-01-02


# General infos
name: "Basic_model"
header: "test model and benchmark for quickly assessing validation pipeline"
location: "data"

# Compilation
compilation:
    directory: "model"
    files:
      compartments: "Compartments.tsv"
      output_parameters: "output_parameters.txt"  # This file is generated upon compilation
      ratelaws: "Ratelaws.tsv"
      species: "Species.tsv"

# Simulation
simulation:
    directory: "simulation"    
    files:
      genes_regulation:
      omics:

# Experiment
experiments:
    directory: "experiments"
    name: "experiment_1"  # Optional

