# SPARCED Standard
# Last update: 2025-01-25


# General infos
name: "SPARCED_standard"
header: "Erdem et al., Nat Commun 2022"
location: "data"

# Compilation
compilation:
    directory: "model"
    files:
      compartments: "standard_Compartments.txt"
      output_parameters: "output_parameters.txt"  # This file is generated upon compilation
      ratelaws: "standard_Ratelaws2.txt"
      species: "standard_Species.txt"

# Simulation
simulation:
    directory: "simulation"    
    files:
      genes_regulation: "standard_GeneReg.txt"
      omics: "standard_OmicsData.txt"

# Experiment
experiments:
    directory: "experiments"
    name: "experiment_1"  # Optional

